projects:
  ManagedBills:
    schemaPath: src/graphql/schema.json
    includes:
      - amplify/backend/api/ManagedBills
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: vggkroaiz5hptju24ppniektta
extensions:
  amplify:
    version: 3
