/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:cb3f96be-2ea8-4a61-8638-d46b2506f0fa",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_zuXp6xWTL",
    "aws_user_pools_web_client_id": "2kd0vl8jbjjn9ahuaidj0b6nhu",
    "oauth": {},
    "aws_content_delivery_bucket": "account.managedbills.com-dev",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "http://account.managedbills.com-dev.s3-website.eu-west-2.amazonaws.com",
    "aws_user_files_s3_bucket": "managedbillsupload100003-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://qa3cou2ygnbtfgcwewn4jgiezy.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "null",
    "cookie_storage": {
        "domain": ".managedbills.com",
        "secure": "false"
    }
};


export default awsmobile;
